"""empty message

Revision ID: c79ca385c7e7
Revises: 4ce541b1cb27
Create Date: 2019-05-13 18:54:34.110896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79ca385c7e7'
down_revision = '4ce541b1cb27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('collection', sa.String(length=999), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'collection')
    # ### end Alembic commands ###
